### ISSUE TITLE
Xmas commission

### ISSUE THREAD

**Issue by Irostovsky** [nythonore/test-code-task-junior-django#1]
Hello @nythonore 
I m Ivan from the GuestReady.

Thanks for doing the test task.
I need to clarify couple details before going forward:
1. Imagine that the marketing team wants to set the 12% for Dec and 11% for Jan because of Xmas. How the code should be changed?
2. What your code will return in case I pass the wrong date, ie 'some bad date'? How to test it?

Waiting for your response. 
Thanks!

**Comment by nythonore** [comment]
Hi @Irostovsky 

Thanks for the feedback

1. In that case instead of having many if conditions we can create dict that will hold months and their commissions, you can check it here: https://github.com/nythonore/test-code-task-junior-django/commit/64e015751795aaf8e0b3ef31c09f4fca681d15ff#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1
2. I added its test you can check it here: https://github.com/nythonore/test-code-task-junior-django/commit/64e015751795aaf8e0b3ef31c09f4fca681d15ff#diff-f455f302936271d755f6892d443786094d2607b505ff180ca817cb9eeabe1e5e

Thanks.

**Comment by Irostovsky** [comment]
Hi @nythonore 
Agree, it is an acceptable solution.
Lets go forward. Agency will contact you.
